name: CD

on:
  push:
    branches:
      master

jobs:
  build:
    env:
      PYTHONPATH: yugiohbot
      CLOUDSDK_CORE_DISABLE_PROMPTS: 1
      ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
      PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: hashicorp/setup-terraform@v1
      - run: terraform --version

      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Install GCP Components
        run: |
          gcloud info
          gcloud --quiet components install beta
          gcloud --quiet components update

      - name: Setup Deployment
        run: |
          mkdir -p deployment/function/
          cp -a yugiohbot/. deployment/function/
          chmod +x ./deployment/deploy.sh

      - name: Run Deployment
        run: deployment/deploy.sh