name: CI

on: [push, pull_request]

jobs:
  build:
    env:
      PYTHONPATH: yugiohbot
      ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
      PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r yugiohbot/requirements.txt

      # No tests here, at least not yet.